### ISSUE TITLE
Tutorials: Running Your First Experiment does not work with v0.8

### ISSUE THREAD

**Issue by vililichi** [thousandbrainsproject/tbp.monty#386]
### Describe the bug

The tutorial *Running Your First Experiment* for v0.8 from https://github.com/thousandbrainsproject/tbp.monty/blob/main/docs/how-to-use-monty/tutorials/running-your-first-experiment.md does not work.

When starting the experiment, the following error is raised:
```
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    CONFIGS = load_configs(experiments)
  File "/home/vililichi/Desktop/test_monty/tbp.monty/benchmarks/configs/load.py", line 39, in load_configs
    configs.update(select_config(experiment))
  File "/home/vililichi/Desktop/test_monty/tbp.monty/benchmarks/configs/load.py", line 110, in select_config
    from benchmarks.configs.my_experiments import CONFIGS as MY_EXPERIMENTS
  File "/home/vililichi/Desktop/test_monty/tbp.monty/benchmarks/configs/my_experiments.py", line 4, in <module>
    from tbp.monty.frameworks.config_utils.config_args import (
ImportError: cannot import name 'SingleCameraMontyConfig' from 'tbp.monty.frameworks.config_utils.config_args' (/home/vililichi/Desktop/test_monty/tbp.monty/src/tbp/monty/frameworks/config_utils/config_args.py)
```

The class SingleCameraMontyConfig was remove with the pull https://github.com/thousandbrainsproject/tbp.monty/pull/370.

**Comment by tristanls** [comment]
Thank you for the report @vililichi and apologies for this not working.

**Comment by scottcanoe** [comment]
Hi @vililichi, thanks for bringing this up. I'm working on a fix with [this PR](https://github.com/thousandbrainsproject/tbp.monty/pull/389). You can give that a shot if you like.

**Comment by scottcanoe** [comment]
Hi @vililichi, this issue should now be fixed. Thanks again for raising the issue, it's super helpful for us.
