### ISSUE TITLE
AttributeError: module 'tbp.monty.frameworks.environments.embodied_data' has no attribute 'EnvironmentDataset'

### ISSUE THREAD

**Issue by duaashabanali** [thousandbrainsproject/tbp.monty#488]
### Describe the bug

When running "python benchmarks/run.py -e first_experiment" which is in the [first tutorial](https://thousandbrainsproject.readme.io/docs/running-your-first-experiment) , I get the following error:
```
(tbp.monty) ➜  tbp.monty git:(main) ✗ python benchmarks/run.py -e first_experiment
Traceback (most recent call last):
  File "benchmarks/run.py", line 42, in <module>
    CONFIGS = load_configs(experiments)
  File "/Users/duaaali/tbp/tbp.monty/benchmarks/configs/load.py", line 39, in load_configs
    configs.update(select_config(experiment))
  File "/Users/duaaali/tbp/tbp.monty/benchmarks/configs/load.py", line 110, in select_config
    from benchmarks.configs.my_experiments import CONFIGS as MY_EXPERIMENTS
  File "/Users/duaaali/tbp/tbp.monty/benchmarks/configs/my_experiments.py", line 48, in <module>
    dataset_class=ED.EnvironmentDataset,
AttributeError: module 'tbp.monty.frameworks.environments.embodied_data' has no attribute 'EnvironmentDataset'
```

**Comment by tristanls** [comment]
This appears to be caused by #448.

**Comment by jeremyshoemaker** [comment]
Hi @duaashabanali. Thanks for reporting this issue. We recently refactored and removed the **EnvironmentDataset** class as part of the work that @tristanls mentioned, but it looks like we forgot to update the tutorials in the documentation.

We'll work on updating the tutorials, but in the mean time you should be able to get unstuck by removing the `dataset_class=ED.EnvironmentDataset` line in the configuration dictionary anywhere you find it.

**Comment by annark** [comment]
This issue was caused by my [recent PR](https://github.com/thousandbrainsproject/tbp.monty/pull/448). I'm in the process of updating the documentation and tutorials now, with a PR that fixes this.

**Comment by jeremyshoemaker** [comment]
@annark I think I got them all in my PR, but feel free to open another one if you find anything I missed.
